openapi: 3.0.0
info:
  title: API de Productos
  description: API para gestionar productos en un e-commerce
  version: 1.0.0
paths:
  /api/productos:
    get:
      summary: Obtener todos los productos
      responses:
        200:
          description: Listado de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Producto'

    post:
      summary: Crear un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        201:
          description: Producto creado

  /api/productos/{id}:
    get:
      summary: Obtener un producto por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Producto encontrado
        404:
          description: Producto no encontrado
    put:
      summary: Actualizar un producto por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        200:
          description: Producto actualizado
        404:
          description: Producto no encontrado
    delete:
      summary: Eliminar un producto por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Producto eliminado
        404:
          description: Producto no encontrado

components:
  schemas:
    Producto:
      type: object
      properties:
        nombre:
          type: string
        precio:
          type: number
        imagen:
          type: string
        descripcion:
          type: string
